name: "main"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - run: |
          go get -v -t -d ./...
      - run: go build -v main.go
#      - run: go test ./tests/... -v
#  package:
#    name: Package
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: google-github-actions/setup-gcloud@master
#        with:
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#          export_default_credentials: true
#      - name: Package
#        run: gcloud builds submit --tag gcr.io/pinger-useast/pinger-api:latest --project pinger-useast
#        working-directory: services/pinger-api
